export interface TarotCard {
  id: string;
  name: string;
  arcana: 'major' | 'minor';
  suit?: 'wands' | 'cups' | 'swords' | 'pentacles';
  number?: number;
  keywords: string[];
  upright: {
    meaning: string;
    love: string;
    career: string;
  };
  reversed: {
    meaning: string;
    love: string;
    career: string;
  };
}

export const TAROT_DECK: TarotCard[] = [
  {
    id: 'the-fool',
    name: 'The Fool',
    arcana: 'major',
    number: 0,
    keywords: ['beginnings', 'innocence', 'spontaneity', 'free spirit'],
    upright: {
      meaning: 'The Fool represents new beginnings, innocence, and spontaneity. This card suggests taking a leap of faith, embarking on a new journey with optimism and trust. Embrace the unknown with childlike wonder and openness to experience.',
      love: 'New romantic adventures await. Be open to unexpected connections and approach love with fresh eyes. Take a chance on romance.',
      career: 'A new career path or project is calling. Take calculated risks and trust your instincts. Innovation and fresh perspectives will serve you well.',
    },
    reversed: {
      meaning: 'Recklessness, poor judgment, or naivety. You may be acting without thinking or ignoring important details. Exercise caution before making major decisions.',
      love: 'Rushing into relationships without consideration. Guard against being too impulsive or ignoring red flags.',
      career: 'Poor planning or unrealistic expectations. Take time to prepare and consider consequences before acting.',
    },
  },
  {
    id: 'the-magician',
    name: 'The Magician',
    arcana: 'major',
    number: 1,
    keywords: ['manifestation', 'power', 'skill', 'concentration'],
    upright: {
      meaning: 'The Magician represents manifestation and resourcefulness. You have all the tools you need to achieve your goals. Channel your willpower and focus to transform ideas into reality.',
      love: 'The power to manifest the relationship you desire. Clear communication and confident action attract romance.',
      career: 'Your skills and talents position you for success. Take initiative and showcase your abilities. Creative solutions emerge.',
    },
    reversed: {
      meaning: 'Manipulation, unused potential, or trickery. Your talents may be misdirected or you\'re being deceived. Examine your true intentions.',
      love: 'Manipulation or dishonesty in relationships. Someone may not be showing their true self.',
      career: 'Wasted talent or unethical business practices. Realign your goals with your values.',
    },
  },
  {
    id: 'the-high-priestess',
    name: 'The High Priestess',
    arcana: 'major',
    number: 2,
    keywords: ['intuition', 'mystery', 'subconscious', 'inner voice'],
    upright: {
      meaning: 'The High Priestess embodies intuition, sacred knowledge, and the subconscious mind. Trust your inner voice and pay attention to dreams and instincts. Wisdom comes from within.',
      love: 'Trust your intuition about relationships. Hidden emotions or unspoken feelings need acknowledgment. Mystery deepens connection.',
      career: 'Trust your gut feelings about business decisions. Information may be revealed soon. Practice patience and observation.',
    },
    reversed: {
      meaning: 'Disconnection from intuition, hidden agendas, or repressed feelings. You may be ignoring your inner voice or keeping secrets.',
      love: 'Lack of emotional honesty or hidden aspects in a relationship. Address what remains unspoken.',
      career: 'Important information is being withheld. Trust issues may be present. Seek clarity.',
    },
  },
  {
    id: 'the-empress',
    name: 'The Empress',
    arcana: 'major',
    number: 3,
    keywords: ['abundance', 'nurturing', 'fertility', 'nature'],
    upright: {
      meaning: 'The Empress represents abundance, beauty, and nurturing energy. Creative projects flourish and growth is natural. Connect with nature and embrace sensual pleasures.',
      love: 'Deep emotional connection and nurturing relationships. Romance blooms naturally. Fertility and growth in partnerships.',
      career: 'Creativity and abundance flow. Projects reach fruition. Nurture your ideas and watch them grow.',
    },
    reversed: {
      meaning: 'Creative block, dependence on others, or neglecting self-care. You may be depleted or stifling growth.',
      love: 'Smothering or codependency in relationships. Need for independence or personal space.',
      career: 'Creative blocks or financial insecurity. Restore balance between giving and receiving.',
    },
  },
  {
    id: 'the-emperor',
    name: 'The Emperor',
    arcana: 'major',
    number: 4,
    keywords: ['authority', 'structure', 'control', 'leadership'],
    upright: {
      meaning: 'The Emperor embodies authority, structure, and leadership. Establish order and take control of your situation. Clear boundaries and strategic planning lead to success.',
      love: 'Stability and commitment in relationships. Traditional values and protective energy. Establish clear expectations.',
      career: 'Leadership opportunities arise. Structure and discipline bring success. Assert your authority confidently.',
    },
    reversed: {
      meaning: 'Domination, excessive control, or lack of discipline. Rigidity or abuse of power may be present.',
      love: 'Control issues or inflexibility in relationships. Struggle with commitment or authority.',
      career: 'Tyrannical leadership or lack of organization. Balance control with flexibility.',
    },
  },
  {
    id: 'the-hierophant',
    name: 'The Hierophant',
    arcana: 'major',
    number: 5,
    keywords: ['tradition', 'conformity', 'spiritual wisdom', 'education'],
    upright: {
      meaning: 'The Hierophant represents tradition, spiritual wisdom, and established institutions. Seek guidance from mentors or traditional teachings. Honor conventional wisdom.',
      love: 'Traditional commitment and shared values. Marriage or formal partnership may be indicated. Follow your heart within established norms.',
      career: 'Formal education, mentorship, or following established procedures brings success. Respect traditional approaches.',
    },
    reversed: {
      meaning: 'Rebellion against tradition, unconventional approaches, or personal beliefs over dogma. Question outdated systems.',
      love: 'Non-traditional relationships or unconventional approaches to commitment. Break free from expectations.',
      career: 'Challenge the status quo or find your own path. Innovation over tradition.',
    },
  },
  {
    id: 'the-lovers',
    name: 'The Lovers',
    arcana: 'major',
    number: 6,
    keywords: ['love', 'harmony', 'relationships', 'choices'],
    upright: {
      meaning: 'The Lovers represent deep connections, important choices, and harmony. Alignment of values creates powerful bonds. Make decisions from the heart.',
      love: 'Deep romantic connection and emotional harmony. Significant relationship or important choice in love matters.',
      career: 'Partnership opportunities or important decisions about values. Choose work that aligns with your beliefs.',
    },
    reversed: {
      meaning: 'Disharmony, misalignment of values, or difficult choices. Inner conflict or relationship challenges present themselves.',
      love: 'Relationship struggles or incompatibility. Self-love needs attention before romantic love can flourish.',
      career: 'Value conflicts at work or difficult business partnerships. Realignment needed.',
    },
  },
  {
    id: 'the-chariot',
    name: 'The Chariot',
    arcana: 'major',
    number: 7,
    keywords: ['willpower', 'victory', 'determination', 'control'],
    upright: {
      meaning: 'The Chariot represents willpower, determination, and victory through focused effort. Maintain control and push forward with confidence. Success requires discipline.',
      love: 'Take decisive action in romance. Overcome obstacles through determination. Assert your needs confidently.',
      career: 'Drive and ambition lead to success. Stay focused on your goals. Victory through perseverance.',
    },
    reversed: {
      meaning: 'Lack of direction, loss of control, or aggression. Scattered energy or being pulled in opposing directions.',
      love: 'Relationship moving too fast or lack of emotional control. Slow down and reassess direction.',
      career: 'Lack of focus or opposing forces at work. Regain control and clarify your path.',
    },
  },
  {
    id: 'strength',
    name: 'Strength',
    arcana: 'major',
    number: 8,
    keywords: ['courage', 'patience', 'compassion', 'inner strength'],
    upright: {
      meaning: 'Strength represents inner courage, compassion, and gentle control. Face challenges with grace and patience. True strength comes from the heart, not force.',
      love: 'Patience and compassion strengthen relationships. Show vulnerability and emotional courage.',
      career: 'Quiet confidence and perseverance overcome obstacles. Lead with compassion and inner strength.',
    },
    reversed: {
      meaning: 'Self-doubt, weakness, or lack of confidence. Inner turmoil or using force instead of persuasion.',
      love: 'Insecurity or neediness in relationships. Work on self-confidence before seeking validation.',
      career: 'Lack of confidence or inability to handle pressure. Reconnect with inner strength.',
    },
  },
  {
    id: 'the-hermit',
    name: 'The Hermit',
    arcana: 'major',
    number: 9,
    keywords: ['introspection', 'solitude', 'inner guidance', 'wisdom'],
    upright: {
      meaning: 'The Hermit represents introspection, soul-searching, and inner guidance. Take time for solitude and reflection. Wisdom comes from within and contemplation.',
      love: 'Period of solitude before romance, or deep emotional introspection. Take time to understand yourself.',
      career: 'Step back and reflect on your career path. Seek inner wisdom before making major decisions.',
    },
    reversed: {
      meaning: 'Isolation, loneliness, or withdrawal. You may be too withdrawn or ignoring important social connections.',
      love: 'Excessive isolation preventing romantic connection. Balance alone time with openness to others.',
      career: 'Refusing guidance or isolating yourself from colleagues. Seek mentorship and collaboration.',
    },
  },
  {
    id: 'wheel-of-fortune',
    name: 'Wheel of Fortune',
    arcana: 'major',
    number: 10,
    keywords: ['cycles', 'fate', 'turning point', 'destiny'],
    upright: {
      meaning: 'The Wheel of Fortune represents life cycles, karma, and turning points. Change is inevitable and often positive. Embrace the natural flow of ups and downs.',
      love: 'Positive changes in love life. Destiny brings new opportunities. Go with the flow.',
      career: 'Career luck shifts favorably. Unexpected opportunities arise. Embrace change.',
    },
    reversed: {
      meaning: 'Resistance to change, bad luck, or negative cycles. External forces may feel overwhelming.',
      love: 'Unwelcome changes or repeating negative patterns. Break the cycle.',
      career: 'Setbacks or resistance to necessary changes. Adapt to shifting circumstances.',
    },
  },
  {
    id: 'justice',
    name: 'Justice',
    arcana: 'major',
    number: 11,
    keywords: ['fairness', 'truth', 'law', 'accountability'],
    upright: {
      meaning: 'Justice represents fairness, truth, and karmic balance. Decisions should be made objectively. Truth and accountability bring resolution.',
      love: 'Balanced relationships built on fairness. Truth emerges. Karmic relationships present themselves.',
      career: 'Fair treatment and contracts. Legal matters resolve favorably. Act with integrity.',
    },
    reversed: {
      meaning: 'Unfairness, dishonesty, or lack of accountability. Legal complications or being treated unjustly.',
      love: 'Imbalanced relationships or dishonesty. Address unfair treatment.',
      career: 'Unethical behavior or unfair treatment at work. Legal complications possible.',
    },
  },
  {
    id: 'the-hanged-man',
    name: 'The Hanged Man',
    arcana: 'major',
    number: 12,
    keywords: ['surrender', 'new perspective', 'letting go', 'suspension'],
    upright: {
      meaning: 'The Hanged Man represents surrender, new perspective, and willing sacrifice. Sometimes letting go is the answer. See situations from a different angle.',
      love: 'Surrender control and trust the process. New perspective transforms relationships.',
      career: 'Pause and reassess. Sometimes inaction is the right action. Shift your viewpoint.',
    },
    reversed: {
      meaning: 'Stalling, resistance, or martyrdom. Unwilling to make necessary sacrifices or stuck in old patterns.',
      love: 'Refusing to let go of control or playing the victim. Release unhealthy attachments.',
      career: 'Unnecessary sacrifice or resistance to change. Stop stalling and take action.',
    },
  },
  {
    id: 'death',
    name: 'Death',
    arcana: 'major',
    number: 13,
    keywords: ['endings', 'transformation', 'transition', 'release'],
    upright: {
      meaning: 'Death represents transformation, endings, and new beginnings. Release what no longer serves you. Major life transitions bring growth.',
      love: 'End of a relationship phase or complete transformation. Let go to make room for new love.',
      career: 'Career transformation or major transition. End of one chapter, beginning of another.',
    },
    reversed: {
      meaning: 'Resistance to change, inability to let go, or stagnation. Fear of endings prevents new beginnings.',
      love: 'Holding onto dead relationships. Fear of moving on.',
      career: 'Refusing necessary career changes. Stagnation due to fear.',
    },
  },
  {
    id: 'temperance',
    name: 'Temperance',
    arcana: 'major',
    number: 14,
    keywords: ['balance', 'moderation', 'patience', 'harmony'],
    upright: {
      meaning: 'Temperance represents balance, moderation, and harmony. Find the middle path. Patience and blending opposites create peace.',
      love: 'Balanced, harmonious relationships. Patience and compromise strengthen bonds.',
      career: 'Balanced approach to work. Collaboration and moderation lead to success.',
    },
    reversed: {
      meaning: 'Imbalance, excess, or lack of moderation. Extremes in behavior or inability to find middle ground.',
      love: 'Imbalanced relationships or extreme behavior. Restore equilibrium.',
      career: 'Overwork or lack of work-life balance. Excess in some areas, neglect in others.',
    },
  },
  {
    id: 'the-devil',
    name: 'The Devil',
    arcana: 'major',
    number: 15,
    keywords: ['bondage', 'materialism', 'addiction', 'shadow self'],
    upright: {
      meaning: 'The Devil represents bondage, materialism, and shadow aspects. Examine what holds you captive. Recognize unhealthy attachments or addictions.',
      love: 'Toxic relationships or unhealthy attachments. Codependency or purely physical attraction.',
      career: 'Golden handcuffs or materialism over fulfillment. Examine what truly motivates you.',
    },
    reversed: {
      meaning: 'Breaking free from bondage, overcoming addiction, or reclaiming power. Liberation from what binds you.',
      love: 'Breaking free from toxic relationships. Recognizing and healing unhealthy patterns.',
      career: 'Leaving unfulfilling work or breaking free from materialistic pursuits.',
    },
  },
  {
    id: 'the-tower',
    name: 'The Tower',
    arcana: 'major',
    number: 16,
    keywords: ['upheaval', 'revelation', 'disaster', 'awakening'],
    upright: {
      meaning: 'The Tower represents sudden upheaval, revelation, and necessary destruction. False foundations crumble. Painful but necessary change brings truth.',
      love: 'Sudden relationship upheaval or shocking revelations. Necessary endings clear the way for truth.',
      career: 'Unexpected job loss or business upheaval. Rebuilding on more solid foundations.',
    },
    reversed: {
      meaning: 'Avoiding disaster, delaying the inevitable, or fear of change. The fall may be less severe than imagined.',
      love: 'Avoiding necessary relationship conversations. Delaying inevitable changes.',
      career: 'Resisting necessary career changes. The longer you wait, the harder the fall.',
    },
  },
  {
    id: 'the-star',
    name: 'The Star',
    arcana: 'major',
    number: 17,
    keywords: ['hope', 'inspiration', 'renewal', 'spirituality'],
    upright: {
      meaning: 'The Star represents hope, inspiration, and spiritual renewal. After darkness comes light. Faith and optimism guide you forward.',
      love: 'Renewed hope in love. Healing after heartbreak. Authentic connections emerge.',
      career: 'Inspiration and renewed sense of purpose. Your talents shine. Stay optimistic.',
    },
    reversed: {
      meaning: 'Hopelessness, despair, or lack of faith. Disconnection from inspiration or creative blocks.',
      love: 'Lack of faith in love or self. Feeling unworthy of affection.',
      career: 'Lost sense of purpose or creative inspiration. Reconnect with what inspires you.',
    },
  },
  {
    id: 'the-moon',
    name: 'The Moon',
    arcana: 'major',
    number: 18,
    keywords: ['illusion', 'intuition', 'anxiety', 'subconscious'],
    upright: {
      meaning: 'The Moon represents illusion, intuition, and the subconscious. Not everything is as it seems. Trust your instincts but seek clarity.',
      love: 'Confusion or uncertainty in relationships. Trust your intuition about hidden truths.',
      career: 'Unclear situations or deception possible. Proceed cautiously and seek clarity.',
    },
    reversed: {
      meaning: 'Release of fear, truth revealed, or clarity emerging. Overcoming anxiety and illusion.',
      love: 'Clarity in previously confusing situations. Truth emerges in relationships.',
      career: 'Secrets revealed or misunderstandings cleared. Move forward with confidence.',
    },
  },
  {
    id: 'the-sun',
    name: 'The Sun',
    arcana: 'major',
    number: 19,
    keywords: ['joy', 'success', 'celebration', 'vitality'],
    upright: {
      meaning: 'The Sun represents joy, success, and vitality. Positivity and warmth surround you. Celebrate your achievements and radiate confidence.',
      love: 'Joyful, positive relationships. Happiness and warmth flow naturally. Love shines brightly.',
      career: 'Success and recognition. Your hard work pays off. Enthusiasm brings opportunities.',
    },
    reversed: {
      meaning: 'Temporary setbacks, inner sadness, or blocked happiness. Difficulty seeing the positive.',
      love: 'Relationship difficulties or dampened enthusiasm. Seek the joy within.',
      career: 'Delayed success or lack of recognition. Stay positive despite setbacks.',
    },
  },
  {
    id: 'judgement',
    name: 'Judgement',
    arcana: 'major',
    number: 20,
    keywords: ['reflection', 'reckoning', 'rebirth', 'inner calling'],
    upright: {
      meaning: 'Judgement represents reflection, reckoning, and spiritual awakening. Self-evaluation leads to rebirth. Answer your inner calling.',
      love: 'Judgment and reflection on past relationships. Renewal and second chances.',
      career: 'Career evaluation and potential rebirth. Answer your true calling.',
    },
    reversed: {
      meaning: 'Self-doubt, harsh self-judgment, or avoiding self-evaluation. Inability to forgive yourself or others.',
      love: 'Harsh judgment of self or partner. Release guilt and practice forgiveness.',
      career: 'Fear of judgment or avoiding necessary self-reflection. Release self-doubt.',
    },
  },
  {
    id: 'the-world',
    name: 'The World',
    arcana: 'major',
    number: 21,
    keywords: ['completion', 'accomplishment', 'travel', 'wholeness'],
    upright: {
      meaning: 'The World represents completion, accomplishment, and fulfillment. A cycle concludes successfully. Celebrate your achievements and embrace wholeness.',
      love: 'Complete, harmonious relationships. Lasting love and partnership. Feeling whole.',
      career: 'Achievement of career goals. Successful completion of projects. Recognition and fulfillment.',
    },
    reversed: {
      meaning: 'Incompletion, lack of closure, or seeking shortcuts. One more step needed before success.',
      love: 'Relationship feels incomplete. Need for closure before moving forward.',
      career: 'Projects left unfinished. Take the final steps needed for completion.',
    },
  },
  {
    id: 'ace-of-wands',
    name: 'Ace of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 1,
    keywords: ['inspiration', 'new opportunity', 'growth', 'potential'],
    upright: {
      meaning: 'A new creative beginning or inspired idea. Passionate energy and enthusiasm ignite new ventures. The seed of potential awaits action.',
      love: 'Spark of new romance or renewed passion. Exciting beginning in love matters.',
      career: 'New job opportunity or inspired business idea. Creative breakthrough imminent.',
    },
    reversed: {
      meaning: 'Delays, lack of direction, or missed opportunities. Creative blocks or waning enthusiasm.',
      love: 'Fading passion or missed romantic opportunity. Lack of spark.',
      career: 'Delayed projects or unfocused creative energy. Clarify your direction.',
    },
  },
  {
    id: 'two-of-wands',
    name: 'Two of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 2,
    keywords: ['planning', 'decisions', 'discovery', 'future'],
    upright: {
      meaning: 'Planning and making decisions about the future. World of possibilities awaits. Balance personal power with bold planning.',
      love: 'Considering relationship future. Decision point in romance.',
      career: 'Planning next career moves. Weighing options and considering expansion.',
    },
    reversed: {
      meaning: 'Poor planning, fear of unknown, or lack of follow-through. Indecision paralyzes progress.',
      love: 'Fear of commitment or relationship uncertainty. Avoiding important decisions.',
      career: 'Lack of planning or fear of taking risks. Overwhelmed by options.',
    },
  },
  {
    id: 'three-of-wands',
    name: 'Three of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 3,
    keywords: ['expansion', 'foresight', 'progress', 'exploration'],
    upright: {
      meaning: 'Expansion and forward momentum. Plans are in motion. Foresight and preparation lead to progress.',
      love: 'Relationship expanding into new territory. Long-distance romance or travel together.',
      career: 'Business expansion or career growth. Overseas opportunities.',
    },
    reversed: {
      meaning: 'Obstacles to expansion, delays, or lack of foresight. Plans stall.',
      love: 'Relationship growth obstacles. Distance creates challenges.',
      career: 'Expansion plans face setbacks. Revise strategy.',
    },
  },
  {
    id: 'four-of-wands',
    name: 'Four of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 4,
    keywords: ['celebration', 'harmony', 'homecoming', 'stability'],
    upright: {
      meaning: 'Celebration, harmony, and achievement. Home and stability bring joy. Community and gathering time.',
      love: 'Celebration of relationship milestone. Engagement, wedding, or moving in together.',
      career: 'Work achievement deserving celebration. Positive team environment.',
    },
    reversed: {
      meaning: 'Lack of stability, canceled celebrations, or home troubles. Feeling unwelcome.',
      love: 'Relationship instability or delayed commitment. Celebration postponed.',
      career: 'Workplace disharmony or lack of recognition. Unstable foundation.',
    },
  },
  {
    id: 'five-of-wands',
    name: 'Five of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 5,
    keywords: ['conflict', 'competition', 'tension', 'disagreement'],
    upright: {
      meaning: 'Conflict, competition, and tension. Differing opinions clash. Challenge can lead to growth.',
      love: 'Arguments or competition in relationships. Differing viewpoints need resolution.',
      career: 'Workplace conflict or healthy competition. Navigate office politics.',
    },
    reversed: {
      meaning: 'Avoiding conflict, end of competition, or inner turmoil. Resolution of tension.',
      love: 'Avoiding necessary relationship conversations. Conflict resolution needed.',
      career: 'Conflict resolution or choosing not to compete. Inner work conflicts.',
    },
  },
  {
    id: 'six-of-wands',
    name: 'Six of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 6,
    keywords: ['victory', 'success', 'recognition', 'achievement'],
    upright: {
      meaning: 'Victory, success, and public recognition. Your efforts are acknowledged. Confidence and pride in accomplishments.',
      love: 'Successful relationship or being recognized as a couple. Pride in partnership.',
      career: 'Career success and recognition. Promotion or public acknowledgment.',
    },
    reversed: {
      meaning: 'Lack of recognition, private success, or arrogance. Fall from grace or delayed victory.',
      love: 'Relationship insecurity or lack of appreciation. Ego issues.',
      career: 'Lack of recognition or egotism at work. Success doesn\'t bring expected satisfaction.',
    },
  },
  {
    id: 'seven-of-wands',
    name: 'Seven of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 7,
    keywords: ['perseverance', 'defensiveness', 'challenge', 'standing ground'],
    upright: {
      meaning: 'Standing your ground against challenges. Defensiveness and perseverance required. Protect your position.',
      love: 'Defending relationship against outside forces. Standing up for your partnership.',
      career: 'Defending your position or ideas. Competition requires vigilance.',
    },
    reversed: {
      meaning: 'Giving up, exhaustion, or lack of confidence. Overwhelmed by opposition.',
      love: 'Giving up on relationship too easily. Exhaustion from constant defense.',
      career: 'Backing down from challenges. Overwhelmed by competition.',
    },
  },
  {
    id: 'eight-of-wands',
    name: 'Eight of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 8,
    keywords: ['swift action', 'movement', 'speed', 'progress'],
    upright: {
      meaning: 'Swift action and rapid progress. Things moving quickly. Communication and travel accelerate.',
      love: 'Rapid relationship development. Quick communication or travel to see someone.',
      career: 'Fast-paced work environment. Quick decisions and rapid progress.',
    },
    reversed: {
      meaning: 'Delays, slowdown, or lack of direction. Rushed decisions or miscommunication.',
      love: 'Relationship moving too fast or communication delays. Slow down.',
      career: 'Project delays or scattered energy. Miscommunication at work.',
    },
  },
  {
    id: 'nine-of-wands',
    name: 'Nine of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 9,
    keywords: ['resilience', 'persistence', 'boundaries', 'last stand'],
    upright: {
      meaning: 'Resilience and persistence despite challenges. Nearly at the finish line. Maintain boundaries and keep going.',
      love: 'Relationship resilience. Past hurts make you cautious but don\'t give up.',
      career: 'Almost at career goal. Persist despite obstacles. Protect your boundaries.',
    },
    reversed: {
      meaning: 'Exhaustion, paranoia, or giving up too soon. Struggling to continue.',
      love: 'Emotional walls prevent connection. Exhaustion from past relationships.',
      career: 'Burnout or giving up before completion. Paranoia at work.',
    },
  },
  {
    id: 'ten-of-wands',
    name: 'Ten of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 10,
    keywords: ['burden', 'responsibility', 'stress', 'overload'],
    upright: {
      meaning: 'Heavy burdens and overwhelming responsibility. Carrying too much alone. Success comes with weight.',
      love: 'Relationship feels burdensome. Too much responsibility in partnership.',
      career: 'Work overload and excessive responsibility. Delegate or risk burnout.',
    },
    reversed: {
      meaning: 'Releasing burdens, delegation, or collapse under pressure. Inability to carry the load.',
      love: 'Releasing relationship burdens or letting go of toxic responsibility.',
      career: 'Delegating tasks or walking away from overwhelming work.',
    },
  },
  {
    id: 'page-of-wands',
    name: 'Page of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 11,
    keywords: ['enthusiasm', 'exploration', 'discovery', 'free spirit'],
    upright: {
      meaning: 'Enthusiasm, exploration, and new ideas. Adventurous spirit and willingness to try. Creative messenger.',
      love: 'Exciting new romantic interest or adventurous approach to love.',
      career: 'New creative opportunities or enthusiastic new project. Good news coming.',
    },
    reversed: {
      meaning: 'Lack of direction, procrastination, or being hasty. News delays or false starts.',
      love: 'Immature approach to relationships. Lack of commitment.',
      career: 'Procrastination or unrealistic career ideas. Lack of follow-through.',
    },
  },
  {
    id: 'knight-of-wands',
    name: 'Knight of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 12,
    keywords: ['action', 'adventure', 'passion', 'impulsiveness'],
    upright: {
      meaning: 'Bold action, adventure, and passionate pursuit. Charging forward with confidence. Energy and enthusiasm drive progress.',
      love: 'Passionate, adventurous romance. Charming but possibly impulsive lover.',
      career: 'Taking bold career action. Travel or change of scenery for work.',
    },
    reversed: {
      meaning: 'Recklessness, haste, or lack of follow-through. Arrogance or passive approach.',
      love: 'Reckless romantic behavior or fleeting passion. Commitment issues.',
      career: 'Hasty career decisions or burning bridges. Scattered energy.',
    },
  },
  {
    id: 'queen-of-wands',
    name: 'Queen of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 13,
    keywords: ['confidence', 'determination', 'courage', 'independence'],
    upright: {
      meaning: 'Confidence, courage, and independence. Charismatic energy attracts others. Determination and social ease.',
      love: 'Confident, independent approach to love. Attractive, warm personality.',
      career: 'Leadership with warmth and confidence. Social intelligence at work.',
    },
    reversed: {
      meaning: 'Insecurity, jealousy, or self-centeredness. Demanding or controlling behavior.',
      love: 'Jealousy or possessiveness in relationships. Insecurity masked by bravado.',
      career: 'Workplace jealousy or demanding behavior. Lack of confidence.',
    },
  },
  {
    id: 'king-of-wands',
    name: 'King of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 14,
    keywords: ['leadership', 'vision', 'entrepreneur', 'honor'],
    upright: {
      meaning: 'Natural leadership, vision, and entrepreneurial spirit. Charismatic authority. Honorable and bold.',
      love: 'Passionate, protective partner. Natural leader in relationships.',
      career: 'Leadership success and entrepreneurial ventures. Vision and courage.',
    },
    reversed: {
      meaning: 'Domineering, ruthless, or lack of self-control. Arrogance or ineffective leadership.',
      love: 'Controlling or aggressive in relationships. Ego issues.',
      career: 'Tyrannical leadership or impulsive business decisions. Abuse of power.',
    },
  },
  {
    id: 'ace-of-cups',
    name: 'Ace of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 1,
    keywords: ['love', 'new feelings', 'intuition', 'spiritual opening'],
    upright: {
      meaning: 'New love, emotional beginnings, and spiritual openings. Heart overflows with feelings. Creative and intuitive inspiration.',
      love: 'New love or renewed feelings. Deep emotional connection begins.',
      career: 'Creative inspiration at work. Following your heart in career matters.',
    },
    reversed: {
      meaning: 'Blocked emotions, emptiness, or repressed feelings. Difficulty expressing love.',
      love: 'Emotional unavailability or one-sided feelings. Blocked heart.',
      career: 'Creative blocks or unfulfilling work. Disconnection from passion.',
    },
  },
  {
    id: 'two-of-cups',
    name: 'Two of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 2,
    keywords: ['partnership', 'unity', 'attraction', 'connection'],
    upright: {
      meaning: 'Partnership, mutual attraction, and emotional connection. Unity and balance. Meaningful relationships form.',
      love: 'Deep romantic connection or partnership. Mutual attraction and respect.',
      career: 'Beneficial business partnership. Collaboration and mutual support.',
    },
    reversed: {
      meaning: 'Imbalance in relationships, disconnection, or broken partnerships. One-sided feelings.',
      love: 'Relationship imbalance or lack of connection. Communication breakdown.',
      career: 'Partnership conflicts or lack of collaboration. Misaligned goals.',
    },
  },
  {
    id: 'three-of-cups',
    name: 'Three of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 3,
    keywords: ['celebration', 'friendship', 'community', 'joy'],
    upright: {
      meaning: 'Celebration, friendship, and community. Joyful gatherings and shared happiness. Creative collaboration.',
      love: 'Celebration in relationships or meeting through friends. Social romance.',
      career: 'Team success and workplace camaraderie. Collaborative achievements.',
    },
    reversed: {
      meaning: 'Gossip, isolation, or overindulgence. Lack of social support or excessive partying.',
      love: 'Third party interference or social complications. Overindulgence affecting relationships.',
      career: 'Workplace gossip or lack of team support. Office politics.',
    },
  },
  {
    id: 'four-of-cups',
    name: 'Four of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 4,
    keywords: ['apathy', 'contemplation', 'reevaluation', 'discontent'],
    upright: {
      meaning: 'Apathy, contemplation, and missed opportunities. Feeling disconnected or bored. Time for reevaluation.',
      love: 'Taking relationships for granted or feeling disconnected. Missing romantic opportunities.',
      career: 'Job dissatisfaction or feeling stuck. Opportunity you\'re not seeing.',
    },
    reversed: {
      meaning: 'Renewed interest, awareness, or new opportunities recognized. End of apathy.',
      love: 'Renewed appreciation for partner or opening to new love.',
      career: 'Recognizing opportunities or renewed career motivation.',
    },
  },
  {
    id: 'five-of-cups',
    name: 'Five of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 5,
    keywords: ['loss', 'grief', 'regret', 'disappointment'],
    upright: {
      meaning: 'Loss, grief, and disappointment. Focusing on what\'s lost rather than what remains. Time to process emotions.',
      love: 'Heartbreak or relationship loss. Grief over what could have been.',
      career: 'Job loss or career disappointment. Focus on lessons learned.',
    },
    reversed: {
      meaning: 'Recovery, acceptance, and moving forward. Seeing what remains. Healing begins.',
      love: 'Healing from heartbreak. Opening to new possibilities after loss.',
      career: 'Recovery from setback. Learning from past failures.',
    },
  },
  {
    id: 'six-of-cups',
    name: 'Six of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 6,
    keywords: ['nostalgia', 'childhood', 'memories', 'innocence'],
    upright: {
      meaning: 'Nostalgia, happy memories, and innocence. Past connections resurface. Childhood influences present.',
      love: 'Past love returns or nostalgic approach to romance. Childhood sweetheart.',
      career: 'Returning to past work or working with familiar people. Traditional approaches.',
    },
    reversed: {
      meaning: 'Stuck in past, unwilling to move forward, or outgrowing old connections. Unrealistic nostalgia.',
      love: 'Holding onto past relationships. Need to move forward.',
      career: 'Outdated methods or clinging to past successes. Evolve.',
    },
  },
  {
    id: 'seven-of-cups',
    name: 'Seven of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 7,
    keywords: ['choices', 'illusion', 'fantasy', 'wishful thinking'],
    upright: {
      meaning: 'Many choices, illusion, and fantasy. Overwhelming options or unrealistic dreams. Discernment needed.',
      love: 'Unrealistic romantic expectations or too many options. Fantasy vs reality.',
      career: 'Multiple career options or unrealistic goals. Focus needed.',
    },
    reversed: {
      meaning: 'Clarity, determination, or disillusionment. Making decisions after confusion.',
      love: 'Clear about relationship needs. Reality check in romance.',
      career: 'Career clarity or letting go of unrealistic dreams. Focused decisions.',
    },
  },
  {
    id: 'eight-of-cups',
    name: 'Eight of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 8,
    keywords: ['walking away', 'seeking deeper meaning', 'disappointment', 'withdrawal'],
    upright: {
      meaning: 'Walking away from what no longer serves. Seeking deeper meaning. Spiritual journey or leaving behind disappointment.',
      love: 'Leaving unfulfilling relationship. Seeking deeper emotional connection.',
      career: 'Leaving job for more meaningful work. Spiritual quest.',
    },
    reversed: {
      meaning: 'Fear of moving on, aimless drifting, or accepting less than deserved. Avoiding necessary change.',
      love: 'Afraid to leave unhealthy relationship. Settling for less.',
      career: 'Staying in unfulfilling job. Fear of career change.',
    },
  },
  {
    id: 'nine-of-cups',
    name: 'Nine of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 9,
    keywords: ['wish fulfillment', 'satisfaction', 'contentment', 'gratitude'],
    upright: {
      meaning: 'Wish fulfillment, satisfaction, and contentment. Dreams coming true. Emotional abundance and gratitude.',
      love: 'Relationship satisfaction. Getting what you want in love.',
      career: 'Career satisfaction and achievement of goals. Success.',
    },
    reversed: {
      meaning: 'Dissatisfaction, greed, or unfulfilled wishes. Shallow happiness or taking for granted.',
      love: 'Relationship dissatisfaction despite having what you wanted. Re-evaluate needs.',
      career: 'Success doesn\'t bring expected fulfillment. Greedy or materialistic.',
    },
  },
  {
    id: 'ten-of-cups',
    name: 'Ten of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 10,
    keywords: ['harmony', 'family', 'emotional fulfillment', 'divine love'],
    upright: {
      meaning: 'Harmony, emotional fulfillment, and family happiness. Lasting relationships and divine love. Perfect emotional state.',
      love: 'Deep, lasting love and family harmony. Committed partnership.',
      career: 'Fulfilling work environment. Work-life balance achieved.',
    },
    reversed: {
      meaning: 'Family discord, broken home, or misaligned values. Seeking happiness externally.',
      love: 'Relationship or family problems. Misaligned expectations.',
      career: 'Work-life imbalance. Priorities misaligned.',
    },
  },
  {
    id: 'page-of-cups',
    name: 'Page of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 11,
    keywords: ['creativity', 'intuition', 'curiosity', 'emotional openness'],
    upright: {
      meaning: 'Creative inspiration, intuitive messages, and emotional openness. Curiosity and wonder. New feelings emerge.',
      love: 'New love interest or sweet romantic gesture. Innocent affection.',
      career: 'Creative opportunities or intuitive insights at work. Good emotional news.',
    },
    reversed: {
      meaning: 'Emotional immaturity, creative blocks, or unrealistic. Difficulty expressing feelings.',
      love: 'Emotionally immature or oversensitive. Unrequited feelings.',
      career: 'Creative blocks or disappointed expectations. Emotional drama at work.',
    },
  },
  {
    id: 'knight-of-cups',
    name: 'Knight of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 12,
    keywords: ['romance', 'charm', 'idealism', 'following the heart'],
    upright: {
      meaning: 'Romance, charm, and following the heart. Idealistic proposals and creative pursuit. Emotional invitation.',
      love: 'Romantic proposal or charming suitor. Following your heart in love.',
      career: 'Creative career opportunity. Following passion over practicality.',
    },
    reversed: {
      meaning: 'Moodiness, unrealistic expectations, or disappointment. Jealousy or manipulation.',
      love: 'Unrealistic romantic expectations. Jealousy or moodiness in love.',
      career: 'Unrealistic career dreams or avoiding practical considerations.',
    },
  },
  {
    id: 'queen-of-cups',
    name: 'Queen of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 13,
    keywords: ['compassion', 'intuition', 'emotional security', 'nurturing'],
    upright: {
      meaning: 'Compassion, intuition, and emotional maturity. Nurturing and caring. Deep emotional intelligence.',
      love: 'Emotionally mature, nurturing love. Intuitive understanding in relationships.',
      career: 'Compassionate leadership. Trust your intuition at work.',
    },
    reversed: {
      meaning: 'Emotional insecurity, codependency, or martyrdom. Overwhelmed by emotions.',
      love: 'Codependency or emotional manipulation. Insecurity in relationships.',
      career: 'Emotional overwhelm at work. Taking on others\' problems.',
    },
  },
  {
    id: 'king-of-cups',
    name: 'King of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 14,
    keywords: ['emotional balance', 'diplomacy', 'wisdom', 'compassion'],
    upright: {
      meaning: 'Emotional balance, diplomatic wisdom, and compassionate leadership. Calm control of emotions. Spiritual maturity.',
      love: 'Emotionally balanced, mature partner. Compassionate and supportive.',
      career: 'Wise, diplomatic leadership. Balancing emotion and logic at work.',
    },
    reversed: {
      meaning: 'Emotional manipulation, volatility, or suppressed feelings. Coldness or moodiness.',
      love: 'Emotionally manipulative or unavailable. Mood swings affect relationship.',
      career: 'Emotional volatility at work. Manipulative leadership.',
    },
  },
  {
    id: 'ace-of-swords',
    name: 'Ace of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 1,
    keywords: ['clarity', 'breakthrough', 'truth', 'mental power'],
    upright: {
      meaning: 'Mental clarity, breakthrough, and truth revealed. Cut through confusion. New ideas and intellectual power.',
      love: 'Clear communication in relationships. Truth emerges.',
      career: 'Mental breakthrough or new idea. Clear thinking leads to success.',
    },
    reversed: {
      meaning: 'Confusion, chaos, or lack of clarity. Miscommunication or harsh truths.',
      love: 'Miscommunication or hurtful words. Confusion in relationships.',
      career: 'Mental fog or poor planning. Communication breakdown at work.',
    },
  },
  {
    id: 'two-of-swords',
    name: 'Two of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 2,
    keywords: ['difficult decisions', 'stalemate', 'avoidance', 'truce'],
    upright: {
      meaning: 'Difficult decision, stalemate, or avoidance. Weighing options carefully. Temporary truce.',
      love: 'Relationship decision point or avoiding conflict. Choose.',
      career: 'Career stalemate or difficult choice. Gather information before deciding.',
    },
    reversed: {
      meaning: 'Decision made, confusion cleared, or information revealed. End of stalemate.',
      love: 'Relationship clarity or end of avoidance. Truth surfaces.',
      career: 'Breaking through career indecision. Information comes to light.',
    },
  },
  {
    id: 'three-of-swords',
    name: 'Three of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 3,
    keywords: ['heartbreak', 'sorrow', 'grief', 'pain'],
    upright: {
      meaning: 'Heartbreak, emotional pain, and sorrow. Painful truth or betrayal. Necessary release of pain.',
      love: 'Heartbreak or betrayal. Painful relationship ending.',
      career: 'Disappointment at work or painful truth. Criticism hurts.',
    },
    reversed: {
      meaning: 'Recovery from heartbreak, forgiveness, or releasing pain. Healing begins.',
      love: 'Healing from heartbreak. Forgiveness and moving forward.',
      career: 'Recovery from career setback. Learning from painful experience.',
    },
  },
  {
    id: 'four-of-swords',
    name: 'Four of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 4,
    keywords: ['rest', 'recovery', 'contemplation', 'stillness'],
    upright: {
      meaning: 'Rest, recovery, and contemplation. Take a break to recharge. Stillness brings clarity.',
      love: 'Relationship pause or time apart. Rest from emotional intensity.',
      career: 'Career break or time to recharge. Step back and reflect.',
    },
    reversed: {
      meaning: 'Restlessness, burnout, or returning to activity. Difficulty resting.',
      love: 'Restlessness in relationships or avoiding needed break.',
      career: 'Burnout or inability to rest. Return to work too soon.',
    },
  },
  {
    id: 'five-of-swords',
    name: 'Five of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 5,
    keywords: ['conflict', 'defeat', 'winning at all costs', 'tension'],
    upright: {
      meaning: 'Conflict, defeat, and hollow victory. Winning at all costs. Tension and discord.',
      love: 'Relationship conflict or ego battles. Winning argument but losing connection.',
      career: 'Office politics or unethical competition. Pyrrhic victory.',
    },
    reversed: {
      meaning: 'Reconciliation, making amends, or choosing battles wisely. Release of conflict.',
      love: 'Relationship reconciliation or choosing peace over being right.',
      career: 'End of workplace conflict. Learning from defeat.',
    },
  },
  {
    id: 'six-of-swords',
    name: 'Six of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 6,
    keywords: ['transition', 'change', 'moving on', 'travel'],
    upright: {
      meaning: 'Transition, moving on, and necessary change. Travel or mental shift. Calmer waters ahead.',
      love: 'Relationship transition or moving forward. Leaving past behind.',
      career: 'Career transition or relocation. Moving toward better situation.',
    },
    reversed: {
      meaning: 'Resisting change, stuck in past, or turbulent transition. Difficulty letting go.',
      love: 'Resistance to relationship change. Unable to move forward.',
      career: 'Resisting career change. Rough transition.',
    },
  },
  {
    id: 'seven-of-swords',
    name: 'Seven of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 7,
    keywords: ['deception', 'strategy', 'betrayal', 'stealth'],
    upright: {
      meaning: 'Deception, strategy, and stealth. Someone not being honest. Strategic thinking or theft.',
      love: 'Deception in relationships or lack of honesty. Someone hiding something.',
      career: 'Workplace deception or strategic planning. Intellectual theft.',
    },
    reversed: {
      meaning: 'Coming clean, being caught, or rethinking strategy. Truth revealed.',
      love: 'Confession or caught in lie. Honesty restored.',
      career: 'Deception revealed at work. Honest approach needed.',
    },
  },
  {
    id: 'eight-of-swords',
    name: 'Eight of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 8,
    keywords: ['restriction', 'powerlessness', 'victim mentality', 'limiting beliefs'],
    upright: {
      meaning: 'Restriction, self-imposed limitation, and victim mentality. Feeling trapped but bindings are loose. Power is within.',
      love: 'Feeling trapped in relationship. Self-imposed limitations prevent love.',
      career: 'Feeling stuck in job. Limiting beliefs about career potential.',
    },
    reversed: {
      meaning: 'Release, freedom, and new perspective. Breaking free from limitations.',
      love: 'Breaking free from limiting relationship beliefs. Empowerment.',
      career: 'Career freedom or breaking free from limitations. Self-empowerment.',
    },
  },
  {
    id: 'nine-of-swords',
    name: 'Nine of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 9,
    keywords: ['anxiety', 'worry', 'nightmares', 'fear'],
    upright: {
      meaning: 'Anxiety, worry, and mental anguish. Nightmares and fears worse than reality. Stress and depression.',
      love: 'Anxiety about relationship. Worrying instead of communicating.',
      career: 'Career stress and worry. Anxiety about work performance.',
    },
    reversed: {
      meaning: 'Recovery from anxiety, hope, or releasing worry. Worst is over.',
      love: 'Release of relationship fears. Hope returns.',
      career: 'Career stress lessening. Finding peace of mind.',
    },
  },
  {
    id: 'ten-of-swords',
    name: 'Ten of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 10,
    keywords: ['endings', 'rock bottom', 'betrayal', 'crisis'],
    upright: {
      meaning: 'Painful ending, rock bottom, and betrayal. Crisis point. Worst is over, only up from here.',
      love: 'Painful relationship ending or deep betrayal. Rock bottom in love.',
      career: 'Job loss or career crisis. Betrayal at work. Hitting bottom.',
    },
    reversed: {
      meaning: 'Recovery, regeneration, or avoiding disaster. Rising from the ashes.',
      love: 'Recovery from heartbreak. Avoiding worst-case scenario.',
      career: 'Career recovery or narrowly avoiding disaster. Resurrection.',
    },
  },
  {
    id: 'page-of-swords',
    name: 'Page of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 11,
    keywords: ['curiosity', 'vigilance', 'ideas', 'communication'],
    upright: {
      meaning: 'Curiosity, new ideas, and vigilant awareness. Mental agility and communication. Spy or messenger.',
      love: 'Intellectual connection or careful approach to romance. Communication important.',
      career: 'New ideas at work or investigative work. Stay alert and curious.',
    },
    reversed: {
      meaning: 'Gossip, deception, or haste. All talk, no action. Spying or manipulation.',
      love: 'Gossip affecting relationship or hurtful communication.',
      career: 'Office gossip or hasty decisions. Defensive communication.',
    },
  },
  {
    id: 'knight-of-swords',
    name: 'Knight of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 12,
    keywords: ['action', 'ambition', 'rush', 'directness'],
    upright: {
      meaning: 'Swift action, ambition, and direct communication. Charging ahead with determination. Fast-paced change.',
      love: 'Direct communication in relationships. Quick-moving romance.',
      career: 'Ambitious career moves or fast-paced projects. Direct action.',
    },
    reversed: {
      meaning: 'Recklessness, impatience, or all talk. Aggressive or unfocused energy.',
      love: 'Aggressive communication or rushed relationship. Impatience.',
      career: 'Reckless career decisions or overly aggressive approach.',
    },
  },
  {
    id: 'queen-of-swords',
    name: 'Queen of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 13,
    keywords: ['clarity', 'independence', 'honesty', 'discernment'],
    upright: {
      meaning: 'Clear thinking, independence, and honest communication. Discernment and objectivity. Intellectual strength.',
      love: 'Honest, direct communication in relationships. Independent partner.',
      career: 'Clear professional boundaries. Honest, objective leadership.',
    },
    reversed: {
      meaning: 'Bitterness, coldness, or harsh judgment. Overly critical or vindictive.',
      love: 'Cold or overly critical in relationships. Bitterness from past hurt.',
      career: 'Harsh or vindictive at work. Overly critical leadership.',
    },
  },
  {
    id: 'king-of-swords',
    name: 'King of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 14,
    keywords: ['intellectual power', 'authority', 'truth', 'clarity'],
    upright: {
      meaning: 'Intellectual power, authority, and truth. Clear, analytical thinking. Ethical leadership and justice.',
      love: 'Logical approach to relationships. Honest, ethical partner.',
      career: 'Authoritative leadership. Ethical decisions and clear thinking.',
    },
    reversed: {
      meaning: 'Manipulation, cruel, or abuse of power. Tyrannical or unethical behavior.',
      love: 'Manipulative or emotionally cold. Abuse of intellectual superiority.',
      career: 'Unethical leadership or manipulative tactics. Abuse of authority.',
    },
  },
  {
    id: 'ace-of-pentacles',
    name: 'Ace of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 1,
    keywords: ['opportunity', 'prosperity', 'new venture', 'manifestation'],
    upright: {
      meaning: 'New financial opportunity, prosperity, and material manifestation. Seed of abundance. Grounded new beginning.',
      love: 'Stable, grounded new relationship. Practical approach to love.',
      career: 'New job opportunity or business venture. Financial gain.',
    },
    reversed: {
      meaning: 'Missed opportunity, poor planning, or financial loss. Lack of progress or wasted resources.',
      love: 'Lack of commitment or financial stress affecting relationship.',
      career: 'Missed career opportunity or poor financial planning.',
    },
  },
  {
    id: 'two-of-pentacles',
    name: 'Two of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 2,
    keywords: ['balance', 'adaptability', 'juggling', 'priorities'],
    upright: {
      meaning: 'Balance, adaptability, and juggling multiple priorities. Managing resources and time well. Flexibility required.',
      love: 'Balancing relationship with other life areas. Flexibility needed.',
      career: 'Juggling multiple projects or managing work-life balance.',
    },
    reversed: {
      meaning: 'Imbalance, overwhelm, or poor financial management. Dropping the ball.',
      love: 'Relationship neglected due to other priorities. Poor balance.',
      career: 'Overwhelmed at work or poor time management. Financial mismanagement.',
    },
  },
  {
    id: 'three-of-pentacles',
    name: 'Three of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 3,
    keywords: ['teamwork', 'collaboration', 'skill', 'quality'],
    upright: {
      meaning: 'Teamwork, skilled collaboration, and quality work. Recognition for expertise. Building together.',
      love: 'Working together on shared goals. Building solid relationship foundation.',
      career: 'Team success and recognition. Quality craftsmanship valued.',
    },
    reversed: {
      meaning: 'Lack of teamwork, poor quality, or disorganization. Lack of recognition.',
      love: 'Misaligned goals or lack of cooperation in relationship.',
      career: 'Team dysfunction or subpar work. Lack of recognition.',
    },
  },
  {
    id: 'four-of-pentacles',
    name: 'Four of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 4,
    keywords: ['security', 'control', 'hoarding', 'possession'],
    upright: {
      meaning: 'Security, control, and material possessiveness. Holding tight to resources. Financial stability but rigidity.',
      love: 'Possessiveness or fear of vulnerability in relationships.',
      career: 'Financial security but resistance to change. Hoarding resources.',
    },
    reversed: {
      meaning: 'Generosity, letting go, or financial insecurity. Release of control.',
      love: 'Releasing possessiveness. Opening heart to vulnerability.',
      career: 'Financial loss or overspending. Letting go of control.',
    },
  },
  {
    id: 'five-of-pentacles',
    name: 'Five of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 5,
    keywords: ['hardship', 'poverty', 'isolation', 'worry'],
    upright: {
      meaning: 'Financial hardship, poverty, and feeling left out. Worry about material security. Help is available if you look.',
      love: 'Relationship struggles due to external stress. Feeling unsupported.',
      career: 'Financial hardship or job insecurity. Asking for help.',
    },
    reversed: {
      meaning: 'Recovery from hardship, accepting help, or spiritual poverty. Financial improvement.',
      love: 'Relationship recovery or accepting support. Connection restored.',
      career: 'Financial recovery or accepting help. Improving circumstances.',
    },
  },
  {
    id: 'six-of-pentacles',
    name: 'Six of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 6,
    keywords: ['generosity', 'charity', 'sharing', 'fairness'],
    upright: {
      meaning: 'Generosity, charity, and fair distribution of resources. Giving and receiving in balance. Support flows.',
      love: 'Balanced give and take in relationships. Generosity.',
      career: 'Fair compensation or financial support. Philanthropy.',
    },
    reversed: {
      meaning: 'Selfishness, strings attached, or unfair exchange. Power imbalance through resources.',
      love: 'Imbalanced giving in relationship. Financial manipulation.',
      career: 'Unfair pay or conditional generosity. Debt with strings.',
    },
  },
  {
    id: 'seven-of-pentacles',
    name: 'Seven of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 7,
    keywords: ['patience', 'investment', 'evaluation', 'perseverance'],
    upright: {
      meaning: 'Patience, long-term investment, and evaluation of progress. Pause to assess. Perseverance pays off.',
      love: 'Evaluating relationship progress. Patience with growth.',
      career: 'Career assessment or long-term project evaluation. Patience required.',
    },
    reversed: {
      meaning: 'Impatience, lack of progress, or wasted investment. Poor planning.',
      love: 'Impatience with relationship progress. Questioning investment.',
      career: 'Career frustration or disappointing returns. Reassess strategy.',
    },
  },
  {
    id: 'eight-of-pentacles',
    name: 'Eight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 8,
    keywords: ['mastery', 'skill', 'dedication', 'quality'],
    upright: {
      meaning: 'Mastery, dedication, and skill development. Focused work and attention to detail. Craftsmanship.',
      love: 'Working on relationship skills. Dedication to partnership.',
      career: 'Skill development and career mastery. Quality work recognized.',
    },
    reversed: {
      meaning: 'Lack of focus, mediocrity, or perfectionism. Underdeveloped skills.',
      love: 'Not putting in relationship work. Lack of effort.',
      career: 'Perfectionism or lack of focus at work. Mediocre results.',
    },
  },
  {
    id: 'nine-of-pentacles',
    name: 'Nine of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 9,
    keywords: ['abundance', 'luxury', 'self-sufficiency', 'independence'],
    upright: {
      meaning: 'Abundance, luxury, and self-sufficiency. Financial independence and material success. Enjoying the fruits of labor.',
      love: 'Independence in relationships. Self-sufficient and complete.',
      career: 'Financial success and career achievement. Reaping rewards.',
    },
    reversed: {
      meaning: 'Financial setbacks, overwork, or lack of independence. Materialism or empty luxury.',
      love: 'Too independent for intimate connection. Financial stress affects romance.',
      career: 'Financial loss or overwork without reward. Materialism.',
    },
  },
  {
    id: 'ten-of-pentacles',
    name: 'Ten of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 10,
    keywords: ['wealth', 'legacy', 'family', 'tradition'],
    upright: {
      meaning: 'Wealth, legacy, and family prosperity. Long-term financial security. Generational abundance and tradition.',
      love: 'Committed family-oriented relationship. Long-term partnership.',
      career: 'Career culmination and financial legacy. Generational wealth.',
    },
    reversed: {
      meaning: 'Financial loss, family disputes, or lack of stability. Short-term thinking.',
      love: 'Family disapproval or relationship instability. Traditional conflicts.',
      career: 'Financial instability or lack of retirement planning. Business failure.',
    },
  },
  {
    id: 'page-of-pentacles',
    name: 'Page of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 11,
    keywords: ['ambition', 'opportunity', 'study', 'manifestation'],
    upright: {
      meaning: 'Ambition, new opportunities, and dedication to learning. Manifestation of ideas into reality. Practical planning.',
      love: 'Practical approach to new relationship. Building solid foundation.',
      career: 'New job opportunity or educational pursuit. Career planning.',
    },
    reversed: {
      meaning: 'Procrastination, lack of progress, or unrealistic goals. Poor planning.',
      love: 'Unrealistic expectations or lack of commitment.',
      career: 'Procrastination or missed opportunities. Lack of focus.',
    },
  },
  {
    id: 'knight-of-pentacles',
    name: 'Knight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 12,
    keywords: ['efficiency', 'routine', 'reliability', 'hard work'],
    upright: {
      meaning: 'Efficiency, hard work, and reliability. Methodical progress. Responsible and practical approach.',
      love: 'Reliable, committed partner. Slow but steady relationship progress.',
      career: 'Hard work and dedication. Routine and efficiency at work.',
    },
    reversed: {
      meaning: 'Boredom, laziness, or workaholic tendencies. Stuck in routine.',
      love: 'Boring relationship or lack of romance. Workaholic neglecting partnership.',
      career: 'Laziness or excessive work focus. Stuck in unfulfilling routine.',
    },
  },
  {
    id: 'queen-of-pentacles',
    name: 'Queen of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 13,
    keywords: ['nurturing', 'abundance', 'practicality', 'security'],
    upright: {
      meaning: 'Nurturing abundance, practical wisdom, and security. Grounded energy. Financial and emotional prosperity.',
      love: 'Nurturing, supportive partner. Practical approach to love.',
      career: 'Successful business ventures. Practical, prosperous leadership.',
    },
    reversed: {
      meaning: 'Financial insecurity, self-care neglect, or materialism. Smothering.',
      love: 'Neglecting relationship due to work. Financial stress affects love.',
      career: 'Poor work-life balance or financial mismanagement.',
    },
  },
  {
    id: 'king-of-pentacles',
    name: 'King of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 14,
    keywords: ['wealth', 'success', 'leadership', 'abundance'],
    upright: {
      meaning: 'Wealth, business success, and material mastery. Generous leadership. Financial security and wise investment.',
      love: 'Stable, providing partner. Security and comfort in relationships.',
      career: 'Business success and financial mastery. Wise leadership.',
    },
    reversed: {
      meaning: 'Greed, materialism, or financial failure. Stubborn or controlling.',
      love: 'Materialistic or controlling in relationships. Workaholic.',
      career: 'Business failure or corrupt practices. Greedy or ineffective leadership.',
    },
  },
];

export function getCardBySlug(slug: string): TarotCard | undefined {
  return TAROT_DECK.find(card => card.id === slug);
}

export function getAllCardSlugs(): string[] {
  return TAROT_DECK.map(card => card.id);
}

export function getMajorArcana(): TarotCard[] {
  return TAROT_DECK.filter(card => card.arcana === 'major');
}

export function getMinorArcana(): TarotCard[] {
  return TAROT_DECK.filter(card => card.arcana === 'minor');
}

export function getCardsBySuit(suit: 'wands' | 'cups' | 'swords' | 'pentacles'): TarotCard[] {
  return TAROT_DECK.filter(card => card.suit === suit);
}
